apiVersion: v1
kind: Service
metadata:
  name: {{ include "claude-town.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "claude-town.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhookPort }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "claude-town.selectorLabels" . | nindent 4 }}
