# This rule is not used by the project claude-town itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the claude-town.claude-town.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: claude-town
    app.kubernetes.io/managed-by: kustomize
  name: clauderepository-editor-role
rules:
- apiGroups:
  - claude-town.claude-town.io
  resources:
  - clauderepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - claude-town.claude-town.io
  resources:
  - clauderepositories/status
  verbs:
  - get
