---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - claude-town.claude-town.io
  resources:
  - clauderepositories
  - claudetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - claude-town.claude-town.io
  resources:
  - clauderepositories/finalizers
  - claudetasks/finalizers
  verbs:
  - update
- apiGroups:
  - claude-town.claude-town.io
  resources:
  - clauderepositories/status
  - claudetasks/status
  verbs:
  - get
  - patch
  - update
