apiVersion: claude-town.claude-town.io/v1alpha1
kind: ClaudeTask
metadata:
  labels:
    app.kubernetes.io/name: claude-town
    app.kubernetes.io/managed-by: kustomize
  name: claudetask-sample
spec:
  # TODO(user): Add fields here
